source 'http://rubygems.org'

gem 'rails', '3.0.9'
# gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'omniauth', '0.2.6'
gem 'pg'
gem 'taps'
gem 'simple_form'
gem 'activemerchant', '1.18.0'
gem 'meta_search'
gem 'rake', '0.9.2.2'
