source 'http://rubygems.org'

gem 'rails', '3.0.9'
# gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'omniauth'
gem 'pg'
gem 'taps'
gem 'simple_form'
gem 'activemerchant', '1.18.0'
gem 'meta_search'
gem 'meta_where'
gem 'twitter_bootstrap_form_for'
